name: "Delete DNS Record"
description: "Deletes CloudFlare DNS record"
author: "Kriasoft"

inputs:
  id:
    description: "DNS record ID"
  name:
    description: "DNS record name"
  token:
    description: "CloudFlare API token"
    required: true
  zone:
    description: "CloudFlare zone"
    required: true

runs:
  using: "node16"
  main: "main.js"

branding:
  icon: "at-sign"
  color: "orange"
