name: "CloudFlare Delete DNS Record"
description: "Removes CloudFlare DNS record"
author: "InfraWay"

inputs:
  id:
    description: "DNS record ID"
  name:
    description: "DNS record name"
  token:
    description: "CloudFlare API token"
    required: true
  zone:
    description: "CloudFlare zone"
    required: true

runs:
  using: "node12"
  main: "main.js"

branding:
  icon: "globe"
  color: "green"
